"""Local search package for SQLite FTS-backed matter search."""

from search.core import (
    APPROVED_STATUS,
    ARCHIVED_STATUS,
    COURT_RETURNED_STATUS,
    DRAFT_STATUS,
    FILED_STATUS,
    IMPORTED_STATUS,
    PROTECTED_STATUSES,
    REVIEWED_STATUS,
    SERVED_STATUS,
    SIGNED_STATUS,
    SUPERSEDED_STATUS,
    DocumentRecord,
    DocumentVersionRecord,
    MatterRecord,
    MatterSearchError,
    SearchResult,
    add_document_version,
    create_document,
    create_matter,
    initialize_search_store,
    rebuild_search_index,
    search_documents,
)

__all__ = [
    "APPROVED_STATUS",
    "ARCHIVED_STATUS",
    "COURT_RETURNED_STATUS",
    "DRAFT_STATUS",
    "FILED_STATUS",
    "IMPORTED_STATUS",
    "PROTECTED_STATUSES",
    "REVIEWED_STATUS",
    "SERVED_STATUS",
    "SIGNED_STATUS",
    "SUPERSEDED_STATUS",
    "DocumentRecord",
    "DocumentVersionRecord",
    "MatterRecord",
    "MatterSearchError",
    "SearchResult",
    "add_document_version",
    "create_document",
    "create_matter",
    "initialize_search_store",
    "rebuild_search_index",
    "search_documents",
]
